version: '3'
services:
  static-site:
    image: nginx:alpine
    container_name: static-site
    restart: unless-stopped
    ports:
      - "4000:4000"  # maps host port 80 to container port 80
    volumes:
      - ./my-site:/usr/share/nginx/html:ro
