version: '3'
services:
  linksite:
    image: nginx:alpine
    container_name: linksite
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - web

networks:
  web:
    driver: bridge
