version: '3'
services:
  linksite:
    image: nginx:alpine
    container_name: linksite
    restart: unless-stopped
    ports:
      - "3000"
    networks:
      - web

networks:
  web:
    driver: bridge
